pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "api-gateway"
        DOCKER_TAG = "latest"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Artifact') {
            steps {
                dir('integrated/api-gateway') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('integrated/api-gateway') {
                    sh "docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} ."
                }
            }
        }

        stage('Deploy') {
            steps {
                sh "docker stop ${DOCKER_IMAGE} || true"
                sh "docker rm ${DOCKER_IMAGE} || true"
                sh """
                    docker run -d --name ${DOCKER_IMAGE} \
                    -p 8060:8060 \
                    --link eureka-server:eureka-server \
                    -e EUREKA_SERVER_HOST='eureka-server' \
                    ${DOCKER_IMAGE}:${DOCKER_TAG}
                """
            }
        }
    }
}
