pipeline {
    agent any
    environment {
        DOCKER_IMAGE = "api-gateway"
        DOCKER_TAG = "latest"
        DOCKERHUB_USER = "asmahannachi2"
        SONAR_URL = "http://localhost:9000"
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build Artifact') {
            steps {
                dir('integrated/api-gateway') {
                    sh 'mvn clean package -DskipTests -Dhttps.protocols=TLSv1.2'
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                dir('integrated/api-gateway') {
                    sh "docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} ."
                }
            }
        }
        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh """
                        echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                        docker tag ${DOCKER_IMAGE}:${DOCKER_TAG} ${DOCKERHUB_USER}/${DOCKER_IMAGE}:${DOCKER_TAG}
                        docker push ${DOCKERHUB_USER}/${DOCKER_IMAGE}:${DOCKER_TAG}
                    """
                }
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                script {
                    sh "kubectl apply -f kubernetes/api-gateway.yaml --validate=false"
                    sh "kubectl rollout restart deployment/api-gateway"
                    sh "kubectl rollout status deployment/api-gateway --timeout=5m"
                    echo "✅ API Gateway deployed successfully"
                }
            }
        }
    }
}
