pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "api-gateway"
        DOCKER_TAG = "latest"
        DOCKERHUB_REPO = "wiwi2003/api-gateway"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Artifact') {
            steps {
                dir('integrated/api-gateway') {
                    sh 'mvn clean package -DskipTests -Dhttps.protocols=TLSv1.2'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('integrated/api-gateway') {
                    sh "docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} ."
                }
            }
        }

        // 🔴 AJOUT IMPORTANT
        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                    sh """
                    docker login -u $USER -p $PASS
                    docker tag ${DOCKER_IMAGE}:${DOCKER_TAG} ${DOCKERHUB_REPO}:${DOCKER_TAG}
                    docker push ${DOCKERHUB_REPO}:${DOCKER_TAG}
                    """
                }
            }
        }

        stage('Deploy') {
            steps {
                sh 'kubectl apply -f kubernetes/gateway.yaml --validate=false'
                sh 'kubectl rollout restart deployment api-gateway'
            }
        }
    }
}