pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "application-service"
        DOCKER_TAG = "latest"
        // Remplacez par votre URL SonarQube si différent de localhost
        SONAR_URL = "http://localhost:9000"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Unit Tests') {
            steps {
                dir('integrated/application-service') {
                    sh 'chmod +x mvnw'
                    sh './mvnw test'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir('integrated/application-service') {
                    withCredentials([string(credentialsId: 'SONAR_TOKEN', variable: 'SONAR_TOKEN')]) {
                        sh "./mvnw sonar:sonar -Dsonar.host.url=${SONAR_URL} -Dsonar.login=${SONAR_TOKEN}"
                    }
                }
            }
        }

        stage('Build Artifact') {
            steps {
                dir('integrated/application-service') {
                    sh 'chmod +x mvnw'
                    sh './mvnw clean package -DskipTests'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('integrated/application-service') {
                    sh "docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} ."
                }
            }
        }

        stage('Deploy') {
            steps {
                sh "docker stop ${DOCKER_IMAGE} || true"
                sh "docker rm ${DOCKER_IMAGE} || true"
                sh """
                    docker run -d --name ${DOCKER_IMAGE} \
                    -p 8089:8089 \
                    --link mysql-db:mysql-db \
                    --link eureka-server:eureka-server \
                    -e SPRING_DATASOURCE_URL='jdbc:mysql://mysql-db:3306/learnify_applications?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true' \
                    -e SPRING_DATASOURCE_USERNAME='root' \
                    -e SPRING_DATASOURCE_PASSWORD='votre_mdp' \
                    -e EUREKA_SERVER_HOST='eureka-server' \
                    ${DOCKER_IMAGE}:${DOCKER_TAG}
                """
            }
        }
    }
}
