pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "eureka-server"
        DOCKER_TAG = "latest"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Artifact') {
            steps {
                dir('integrated/eureka-server') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('integrated/eureka-server') {
                    sh "docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} ."
                }
            }
        }

        stage('Deploy') {
            steps {
                sh "docker stop ${DOCKER_IMAGE} || true"
                sh "docker rm ${DOCKER_IMAGE} || true"
                sh """
                    docker run -d --name ${DOCKER_IMAGE} \
                    -p 8761:8761 \
                    ${DOCKER_IMAGE}:${DOCKER_TAG}
                """
            }
        }
    }
}
