pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "frontend-service"
        DOCKER_TAG = "latest"
        DOCKERHUB_REPO = "wiwi2003/frontend-service"
        SONAR_URL = "http://localhost:9000"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('frontend') {
                    sh 'npm install'
                }
            }
        }

        stage('Unit Tests') {
            steps {
                echo "Skipping tests (no Chrome in Jenkins)"
            }
        }

        stage('SonarQube Analysis') {
            when {
                expression { false } // Désactivé temporairement
            }
            steps {
                dir('frontend') {
                    withCredentials([string(credentialsId: 'SONAR_TOKEN', variable: 'SONAR_TOKEN')]) {
                        sh "npx sonar-scanner -Dsonar.host.url=${SONAR_URL} -Dsonar.login=${SONAR_TOKEN}"
                    }
                }
            }
        }

        stage('Build') {
            steps {
                dir('frontend') {
                    sh 'npm run build'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('frontend') {
                    sh "docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} ."
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                    sh '''
                    echo $PASS | docker login -u $USER --password-stdin
                    docker tag frontend-service:latest wiwi2003/frontend-service:latest
                    docker push wiwi2003/frontend-service:latest
                    '''
                }
            }
        }

       stage('Deploy to Kubernetes') {
           steps {
               script {
                   // Déployer Frontend
                   sh "kubectl apply -f kubernetes/frontend.yaml"
                   
                   // Attendre que le déploiement soit prêt
                   sh "kubectl rollout status deployment/frontend -n pidev --timeout=5m"
                   
                   echo "✅ Frontend deployed to Kubernetes successfully"
                   echo "🌐 Access application at: http://NODE_IP:30080"
               }
           }
       }
    }
}