sonar.projectKey=frontend-service
sonar.projectName=frontend-service
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.spec.ts
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/learnhub/lcov.info
