pipeline {
    agent any
    environment {
        DOCKER_IMAGE = "user-service"
        DOCKER_TAG = "latest"
        DOCKERHUB_USER = "asmahannachi2"
        SONAR_URL = "http://localhost:9000"
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Unit Tests') {
            steps {
                dir('integrated/user-service') {
                    sh 'chmod +x mvnw'
                    sh './mvnw test -DskipTests -Dhttps.protocols=TLSv1.2'
                }
            }
        }
        stage('SonarQube Analysis') {
            when {
                expression { false } // Désactivé temporairement
            }
            steps {
                dir('integrated/user-service') {
                    withCredentials([string(credentialsId: 'SONAR_TOKEN', variable: 'SONAR_TOKEN')]) {
                        sh "./mvnw sonar:sonar -Dsonar.host.url=${SONAR_URL} -Dsonar.token=${SONAR_TOKEN} -Dhttps.protocols=TLSv1.2"
                    }
                }
            }
        }
        stage('Build Artifact') {
            steps {
                dir('integrated/user-service') {
                    sh 'chmod +x mvnw'
                    sh './mvnw clean package -DskipTests -Dhttps.protocols=TLSv1.2'
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                dir('integrated/user-service') {
                    sh "docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} ."
                }
            }
        }
        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh """
                        echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                        docker tag ${DOCKER_IMAGE}:${DOCKER_TAG} ${DOCKERHUB_USER}/${DOCKER_IMAGE}:${DOCKER_TAG}
                        docker push ${DOCKERHUB_USER}/${DOCKER_IMAGE}:${DOCKER_TAG}
                    """
                }
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                script {
                    sh "kubectl apply -f kubernetes/user-service.yaml"
                    sh "kubectl rollout status deployment/user-service -n pidev --timeout=8m"
                    echo "✅ User Service deployed successfully"
                }
            }
        }
    }
}
