pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "job-service"
        DOCKER_TAG = "latest"
        SONAR_URL = "http://localhost:9000"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Unit Tests') {
            steps {
                dir('integrated/job-service') {
                    sh './mvnw test'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir('integrated/job-service') {
                    sh "./mvnw sonar:sonar -Dsonar.host.url=${SONAR_URL}"
                }
            }
        }

        stage('Build Artifact') {
            steps {
                dir('integrated/job-service') {
                    sh './mvnw clean package -DskipTests'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('integrated/job-service') {
                    sh "docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} ."
                }
            }
        }

        stage('Deploy') {
            steps {
                sh "docker stop ${DOCKER_IMAGE} || true"
                sh "docker rm ${DOCKER_IMAGE} || true"
                sh "docker run -d --name ${DOCKER_IMAGE} -p 8088:8088 ${DOCKER_IMAGE}:${DOCKER_TAG}"
            }
        }
    }
}
