pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "job-service"
        DOCKER_TAG = "latest"
        SONAR_URL = "http://localhost:9000"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Unit Tests') {
            steps {
                dir('integrated/job-service') {
                    sh 'chmod +x mvnw'
                    sh './mvnw test -Dhttps.protocols=TLSv1.2'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir('integrated/job-service') {
                    withCredentials([string(credentialsId: 'SONAR_TOKEN', variable: 'SONAR_TOKEN')]) {
                        sh "./mvnw sonar:sonar -Dsonar.host.url=${SONAR_URL} -Dsonar.login=${SONAR_TOKEN} -Dhttps.protocols=TLSv1.2"
                    }
                }
            }
        }

        stage('Build Artifact') {
            steps {
                dir('integrated/job-service') {
                    sh 'chmod +x mvnw'
                    sh './mvnw clean package -DskipTests -Dhttps.protocols=TLSv1.2'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('integrated/job-service') {
                    sh "docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} ."
                }
            }
        }

        stage('Deploy') {
            steps {
                sh 'kubectl apply -f kubernetes/backend.yaml --validate=false'
                sh 'kubectl rollout restart deployment job-service'
            }
        }
    }
}
